name: Build Desktop

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.11.0]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages - Desktop
        working-directory: ./core
        run: npm install

      - name: Lint - Core
        working-directory: ./core
        run: npm run lint

      - name: Build - Core
        working-directory: ./core
        run: npm run build

      - name: Link - Core
        working-directory: ./core
        run: npm link

      - name: Install packages - Desktop
        working-directory: ./desktop
        run: npm install

      - name: Link - Desktop
        working-directory: ./desktop
        run: npm link leng-core

      - name: Lint - Desktop
        working-directory: ./desktop
        run: npm run lint

      - name: Build - Desktop
        working-directory: ./desktop
        run: npm run build
