name: Build Core library

on:
  pull_request:
    branches:
      - "*"

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      desktop: ${{ steps.filter.outputs.desktop }}
      web: ${{ steps.filter.outputs.web }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          desktop:
            - 'core/**'
            - 'desktop/**'
          web:
            - 'core/**'
            - 'web/**'

  build-core-library:    
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './core'

    strategy:
      matrix:
        node-version: [18.11.0]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

 build-desktop:    
    needs: changes
    if: ${{ needs.changes.outputs.desktop == 'true' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './desktop'

    strategy:
      matrix:
        node-version: [18.11.0]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm install

      - name: Re-link core library
        run: npm run relink

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

 build-web:    
    needs: changes
    if: ${{ needs.changes.outputs.web == 'true' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './web'

    strategy:
      matrix:
        node-version: [18.11.0]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm install

      - name: Re-link core library
        run: npm run relink

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
