name: Build Web Viewer

on:
  pull_request:
    branches:
      - "*"
    paths:
      - "core/**"
      - "web/**"

jobs:
  build:    
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './web'

    strategy:
      matrix:
        node-version: [18.11.0]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm install

      - name: Re-link core library
        run: npm run relink

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
